### ISSUE TITLE
Can't authorize with OpenId oidc

### ISSUE THREAD

**Issue by faibistes** [SharpTools/SharpReverseProxy#17] opened 2018-03-06 09:23 UTC
I have multple web apps that are authorized via oidc with a custom authorization server. Single sign on works fine, the first one redirects to the authorization server and subsequent ones validate the token in the backchannel.
I want to use SharpReverseProxy for implementing authentication/authorization in some legacy apps (an Arcgis server, specifically). SharpReverseProxy won't redirect nor validate the token. It just returns 401. Here's my configuration (that exact config works fine on the other webs):
```
public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc(); // Just in case. Makes no difference
            JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();
            services.AddSingleton<IClaimsTransformation, ClaimsTransformer>();
            services.AddAuthentication(options =>
            {
                options.DefaultScheme = "Cookies";
                options.DefaultChallengeScheme = "oidc";

            })
                .AddCookie("Cookies")
                .AddOpenIdConnect("oidc", options =>
                {
                    options.SignInScheme = "Cookies";

                    options.Authority = "http://localhost:62408/";
                    options.RequireHttpsMetadata = false;

                    options.ClientId = "mvc";
                    options.SaveTokens = true;
                });
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseAuthentication();
            app.UseMvc(); // Just in case. Makes no difference
            app.UseProxy(new ProxyOptions { BackChannelMessageHandler = null });
            app.UseProxy(new List<ProxyRule> {
                        new ProxyRule {
                            Matcher = uri => uri.AbsoluteUri.Contains("/api/"),
                            Modifier = (req, user) => {
                                var match = Regex.Match(req.RequestUri.AbsolutePath, "/api/(.*)");
                                    req.RequestUri = new Uri(string.Format("http://localhost:65351/{0}",
                                    match.Groups[1].Value)
                                );                
                             },
                            RequiresAuthentication=true
                            
            }});
            
        }


```

**Comment by samusaran** [comment] 2018-03-06 10:10
I'm not familiar with the protocols you are using, but you set `RequiresAuthentication=true` in the proxy settings, that means that you can't actually use it to implement authentication or authorization since the user should be already authenticated to use the reverse proxy middleware. The 401 is probably caused by that.

Also I don't understand why you set UseProxy twice, with the first not actually doing anything. You could just merge the two as:
```csharp
app.UseProxy(new ProxyOptions
{
    ProxyRules = new List<ProxyRule>
    {
        new ProxyRule {
            Matcher = uri => Task.Run(async () => await serviceProvider.GetService<ReverseProxyDelegates>().ProxyUrlMatcher(uri)).Result,
            Modifier = (req, user) => serviceProvider.GetService<ReverseProxyDelegates>().ProxyRequestModifier(req, user).GetAwaiter().GetResult(),
            ResponseModifier = async (res, ctx) => await serviceProvider.GetService<ReverseProxyDelegates>().ProxyResponseModifier(res, ctx),
            PreProcessResponse = false, // la response la processo a mano
            RequiresAuthentication = false
        }
    },
    Reporter = (r) =>
    {
        switch (r.ProxyStatus)
        {
            case ProxyStatus.Proxied:
                logger.LogInformation("Proxied request: {OriginalUri} > {ProxiedUri} took: {Elapsed}ms", r.OriginalUri, r.ProxiedUri, r.Elapsed.Milliseconds);
                break;
            case ProxyStatus.NotProxied:
                logger.LogInformation("Failed to proxy request: {OriginalUri} > {ProxiedUri} took: {Elapsed}ms", r.OriginalUri, r.ProxiedUri, r.Elapsed.Milliseconds);
                break;
        }
    },
    BackChannelMessageHandler = new HttpClientHandler()
    {
        AutomaticDecompression = System.Net.DecompressionMethods.GZip | System.Net.DecompressionMethods.Deflate,
        AllowAutoRedirect = true,
        CookieContainer = new System.Net.CookieContainer()
    }
});
```

**Comment by faibistes** [comment] 2018-03-06 12:32
Yes, I didn't need two UseProxy(), that was a mistake. However, it makes no difference.
I'm not sure if I understand RequiresAuthentication. Is there a way I can authenticate in the proxy (using any auth middleware)? I've tried Basic authentication too.

**Comment by samusaran** [comment] 2018-03-06 12:46
RequiresAuthentication is used to secure the access to the reverse proxy middleware by checking if the current identity is actually authenticated. In your pipeline there is no authentication before `UseProxy()` (`UseAuthentication()` just enables authentication for the middlewares that follows it, but it does not authenticate anyone.)
So if I got it right, you want to use your OpenId authentication _before_ the reverse proxy.

I had the same problem using WsFederation, and I solved like this:
```csharp
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, IServiceProvider serviceProvider)
{
    // various configurations cut out...

    app.UseAuthentication();
    app.UseMvc();

    // WsFederation Auth
    app.Use(async (context, next) =>
    {
        // DefaultAuthenticateScheme causes User to be set
        var user = context.User;

        // Not authenticated
        if (user == null || !user.Identities.Any(identity => identity.IsAuthenticated))
        {
            // This is what [Authorize] calls
            await context.ChallengeAsync();

            return;
        }
        else
            await next();
    });

    // Reverse proxy
    app.UseProxy(...);
}
```

What I am doing here is authenticating the user before the pipeline gets to the ReverseProxy Middleware. I don't know if OpenId uses `ChallengeAsync()` or one of the other methods like `AuthenticateAsync()`, so just see what works for you.

**Comment by faibistes** [comment] 2018-03-06 14:16
Thank you very much! That did the trick.

**Comment by samusaran** [comment] 2018-03-17 12:33
@andrecarlucci you can close this!

**Closed as completed** 2018-03-26 13:55 UTC
